// Bilingual content for all service detail pages
export interface ServiceContent {
  id: string;
  slug: string;
  icon: string;
  titleMs: string;
  titleEn: string;
  descriptionMs: string;
  descriptionEn: string;
  benefitsMs: string[];
  benefitsEn: string[];
  processMs: { step: number; title: string; description: string }[];
  processEn: { step: number; title: string; description: string }[];
  suitableForMs: string[];
  suitableForEn: string[];
  faqMs: { question: string; answer: string }[];
  faqEn: { question: string; answer: string }[];
}

export const SERVICE_CONTENT: ServiceContent[] = [
  {
    id: 'general-treatment',
    slug: 'rawatan-umum',
    icon: 'Stethoscope',
    titleMs: 'Rawatan Umum',
    titleEn: 'General Treatment',
    descriptionMs: 'Perkhidmatan rawatan kesihatan am untuk pelbagai masalah kesihatan harian. Doktor kami berpengalaman dalam mendiagnosis dan merawat pelbagai keadaan perubatan.',
    descriptionEn: 'General healthcare services for various daily health issues. Our doctors are experienced in diagnosing and treating a wide range of medical conditions.',
    benefitsMs: [
      'Pemeriksaan kesihatan menyeluruh',
      'Rawatan penyakit kronik',
      'Pengurusan tekanan darah tinggi & kencing manis',
      'Surat cuti sakit (MC) dan rujukan',
      'Vaksinasi & imunisasi',
    ],
    benefitsEn: [
      'Comprehensive health examinations',
      'Chronic disease treatment',
      'High blood pressure & diabetes management',
      'Medical certificates (MC) and referrals',
      'Vaccinations & immunizations',
    ],
    processMs: [
      { step: 1, title: 'Pendaftaran', description: 'Daftar di kaunter dan tunggu giliran anda.' },
      { step: 2, title: 'Pemeriksaan', description: 'Doktor akan memeriksa anda dengan teliti.' },
      { step: 3, title: 'Diagnosis', description: 'Doktor akan menerangkan keadaan kesihatan anda.' },
      { step: 4, title: 'Rawatan', description: 'Ubat akan diberikan atau rujukan dibuat jika perlu.' },
    ],
    processEn: [
      { step: 1, title: 'Registration', description: 'Register at the counter and wait for your turn.' },
      { step: 2, title: 'Examination', description: 'The doctor will examine you thoroughly.' },
      { step: 3, title: 'Diagnosis', description: 'The doctor will explain your health condition.' },
      { step: 4, title: 'Treatment', description: 'Medication will be provided or referral made if necessary.' },
    ],
    suitableForMs: ['Semua peringkat umur', 'Keluarga', 'Warga emas', 'Kanak-kanak'],
    suitableForEn: ['All age groups', 'Families', 'Elderly', 'Children'],
    faqMs: [
      { question: 'Adakah saya perlu buat temujanji?', answer: 'Tidak, anda boleh datang terus ke klinik. Namun, temujanji boleh membantu mengurangkan masa menunggu.' },
      { question: 'Berapa lama masa menunggu?', answer: 'Masa menunggu bergantung kepada bilangan pesakit. Biasanya antara 15-30 minit.' },
      { question: 'Adakah klinik menerima panel?', answer: 'Ya, kami menerima pelbagai panel syarikat. Sila bawa kad panel anda.' },
      { question: 'Bolehkah saya dapatkan MC?', answer: 'Ya, doktor akan menilai keadaan anda dan memberikan MC jika diperlukan.' },
      { question: 'Adakah vaksinasi tersedia?', answer: 'Ya, kami menyediakan pelbagai vaksinasi termasuk vaksin selesema dan tetanus.' },
    ],
    faqEn: [
      { question: 'Do I need an appointment?', answer: 'No, you can walk in directly. However, appointments can help reduce waiting time.' },
      { question: 'How long is the waiting time?', answer: 'Waiting time depends on the number of patients. Usually between 15-30 minutes.' },
      { question: 'Does the clinic accept panel cards?', answer: 'Yes, we accept various company panels. Please bring your panel card.' },
      { question: 'Can I get an MC?', answer: 'Yes, the doctor will assess your condition and provide an MC if required.' },
      { question: 'Are vaccinations available?', answer: 'Yes, we provide various vaccinations including flu and tetanus vaccines.' },
    ],
  },
  {
    id: 'cold-flu',
    slug: 'sakit-tekak-selsema-demam',
    icon: 'Thermometer',
    titleMs: 'Sakit Tekak / Selsema / Demam',
    titleEn: 'Sore Throat / Cold / Fever',
    descriptionMs: 'Rawatan cepat dan berkesan untuk jangkitan saluran pernafasan atas termasuk sakit tekak, selsema, dan demam. Dapatkan rawatan segera untuk pulih dengan lebih cepat.',
    descriptionEn: 'Fast and effective treatment for upper respiratory tract infections including sore throat, cold, and fever. Get immediate treatment for faster recovery.',
    benefitsMs: [
      'Diagnosis cepat dan tepat',
      'Rawatan simptom dengan ubat berkesan',
      'Ujian pantas untuk Influenza/COVID jika perlu',
      'Nasihat pencegahan jangkitan',
      'Rawatan komplikasi jika ada',
    ],
    benefitsEn: [
      'Quick and accurate diagnosis',
      'Symptom treatment with effective medication',
      'Rapid tests for Influenza/COVID if needed',
      'Infection prevention advice',
      'Treatment of complications if any',
    ],
    processMs: [
      { step: 1, title: 'Penilaian Simptom', description: 'Doktor akan bertanya tentang simptom anda.' },
      { step: 2, title: 'Pemeriksaan Fizikal', description: 'Pemeriksaan tekak, telinga, dan dada.' },
      { step: 3, title: 'Ujian Pantas', description: 'Ujian COVID/Influenza jika diperlukan.' },
      { step: 4, title: 'Rawatan', description: 'Ubat diberikan mengikut keadaan.' },
    ],
    processEn: [
      { step: 1, title: 'Symptom Assessment', description: 'Doctor will ask about your symptoms.' },
      { step: 2, title: 'Physical Examination', description: 'Examination of throat, ears, and chest.' },
      { step: 3, title: 'Rapid Test', description: 'COVID/Influenza test if required.' },
      { step: 4, title: 'Treatment', description: 'Medication given according to condition.' },
    ],
    suitableForMs: ['Dewasa', 'Kanak-kanak', 'Warga emas', 'Pekerja pejabat'],
    suitableForEn: ['Adults', 'Children', 'Elderly', 'Office workers'],
    faqMs: [
      { question: 'Bilakah saya perlu jumpa doktor untuk demam?', answer: 'Jika demam melebihi 3 hari, suhu melebihi 39°C, atau ada simptom lain yang membimbangkan.' },
      { question: 'Adakah antibiotik diperlukan?', answer: 'Tidak semua jangkitan memerlukan antibiotik. Doktor akan menilai sama ada ia jangkitan virus atau bakteria.' },
      { question: 'Berapa lama untuk pulih?', answer: 'Kebanyakan jangkitan ringan pulih dalam 5-7 hari dengan rawatan yang betul.' },
      { question: 'Bolehkah saya pergi kerja?', answer: 'Disyorkan untuk berehat di rumah terutama jika masih demam atau simptom teruk.' },
      { question: 'Adakah ia berjangkit?', answer: 'Ya, kebanyakan jangkitan saluran pernafasan adalah berjangkit. Amalkan kebersihan tangan.' },
    ],
    faqEn: [
      { question: 'When should I see a doctor for fever?', answer: 'If fever persists beyond 3 days, temperature exceeds 39°C, or there are other concerning symptoms.' },
      { question: 'Are antibiotics needed?', answer: 'Not all infections require antibiotics. The doctor will assess whether it is a viral or bacterial infection.' },
      { question: 'How long to recover?', answer: 'Most mild infections recover within 5-7 days with proper treatment.' },
      { question: 'Can I go to work?', answer: 'It is recommended to rest at home especially if still having fever or severe symptoms.' },
      { question: 'Is it contagious?', answer: 'Yes, most respiratory infections are contagious. Practice good hand hygiene.' },
    ],
  },
  {
    id: 'rapid-tests',
    slug: 'ujian-pantas',
    icon: 'TestTube',
    titleMs: 'Ujian Pantas: Influenza / COVID / RSV / Adenovirus',
    titleEn: 'Rapid Tests: Influenza / COVID / RSV / Adenovirus',
    descriptionMs: 'Ujian diagnostik pantas untuk mengesan jangkitan virus dengan tepat termasuk Influenza A & B, COVID-19, RSV dan Adenovirus. Keputusan dalam masa 15-20 minit untuk rawatan yang lebih tepat sasaran.',
    descriptionEn: 'Rapid diagnostic tests to accurately detect viral infections including Influenza A & B, COVID-19, RSV and Adenovirus. Results within 15-20 minutes for more targeted treatment.',
    benefitsMs: [
      'Keputusan dalam 15-20 minit',
      'Ujian Influenza A & B',
      'Ujian COVID-19',
      'Ujian RSV (Respiratory Syncytial Virus)',
      'Ujian Adenovirus',
      'Diagnosis tepat untuk rawatan berkesan',
      'Mengelakkan penggunaan antibiotik tidak perlu',
      'Nasihat pengasingan jika positif',
    ],
    benefitsEn: [
      'Results within 15-20 minutes',
      'Influenza A & B testing',
      'COVID-19 testing',
      'RSV (Respiratory Syncytial Virus) testing',
      'Adenovirus testing',
      'Accurate diagnosis for effective treatment',
      'Avoid unnecessary antibiotic use',
      'Isolation advice if positive',
    ],
    processMs: [
      { step: 1, title: 'Konsultasi', description: 'Doktor akan menilai simptom anda.' },
      { step: 2, title: 'Pengambilan Sampel', description: 'Swab hidung atau tekak diambil.' },
      { step: 3, title: 'Ujian Dijalankan', description: 'Ujian dilakukan di klinik.' },
      { step: 4, title: 'Keputusan & Rawatan', description: 'Keputusan dibincang dan rawatan dimulakan.' },
    ],
    processEn: [
      { step: 1, title: 'Consultation', description: 'Doctor will assess your symptoms.' },
      { step: 2, title: 'Sample Collection', description: 'Nasal or throat swab is taken.' },
      { step: 3, title: 'Test Performed', description: 'Test is conducted at the clinic.' },
      { step: 4, title: 'Results & Treatment', description: 'Results discussed and treatment initiated.' },
    ],
    suitableForMs: ['Pesakit dengan simptom selesema', 'Demam dengan batuk', 'Kontak rapat kes positif', 'Sebelum perjalanan', 'Kanak-kanak dengan simptom selsema'],
    suitableForEn: ['Patients with flu symptoms', 'Fever with cough', 'Close contacts of positive cases', 'Before traveling', 'Children with cold symptoms'],
    faqMs: [
      { question: 'Apakah ujian pantas yang disediakan?', answer: 'Kami menyediakan ujian pantas untuk Influenza A, Influenza B, COVID-19, RSV dan Adenovirus.' },
      { question: 'Berapa tepat ujian pantas ini?', answer: 'Ujian pantas kami mempunyai ketepatan lebih 90% untuk semua jenis virus yang diuji.' },
      { question: 'Apakah Adenovirus?', answer: 'Adenovirus adalah virus yang menyebabkan jangkitan saluran pernafasan, mata, dan usus. Ia biasa berlaku pada kanak-kanak.' },
      { question: 'Adakah ujian ini sakit?', answer: 'Swab hidung mungkin sedikit tidak selesa tetapi ia cepat dan tidak menyakitkan.' },
      { question: 'Berapa kos ujian?', answer: 'Harga berbeza mengikut jenis ujian. Sila hubungi klinik untuk maklumat harga terkini.' },
      { question: 'Apa perlu buat jika positif?', answer: 'Doktor akan memberikan rawatan dan nasihat pengasingan yang sesuai.' },
      { question: 'Boleh ujian untuk anak kecil?', answer: 'Ya, ujian ini sesuai untuk semua peringkat umur termasuk bayi dan kanak-kanak.' },
    ],
    faqEn: [
      { question: 'What rapid tests are available?', answer: 'We provide rapid tests for Influenza A, Influenza B, COVID-19, RSV and Adenovirus.' },
      { question: 'How accurate are these rapid tests?', answer: 'Our rapid tests have over 90% accuracy for all tested virus types.' },
      { question: 'What is Adenovirus?', answer: 'Adenovirus is a virus that causes respiratory, eye, and intestinal infections. It commonly occurs in children.' },
      { question: 'Is the test painful?', answer: 'The nasal swab may be slightly uncomfortable but it is quick and painless.' },
      { question: 'What is the test cost?', answer: 'Prices vary by test type. Please contact the clinic for current pricing.' },
      { question: 'What to do if positive?', answer: 'The doctor will provide appropriate treatment and isolation advice.' },
      { question: 'Can children be tested?', answer: 'Yes, this test is suitable for all ages including infants and children.' },
    ],
  },
  {
    id: 'nebulizer',
    slug: 'nebulizer',
    icon: 'Wind',
    titleMs: 'Terapi Nebulizer',
    titleEn: 'Nebulizer Therapy',
    descriptionMs: 'Rawatan nebulizer untuk masalah pernafasan seperti asma, bronkitis, dan sesak nafas. Ubat dihidu terus ke paru-paru untuk kesan yang lebih cepat.',
    descriptionEn: 'Nebulizer treatment for respiratory problems such as asthma, bronchitis, and shortness of breath. Medication is inhaled directly to the lungs for faster effect.',
    benefitsMs: [
      'Melegakan sesak nafas dengan cepat',
      'Ubat sampai terus ke paru-paru',
      'Sesuai untuk semua peringkat umur',
      'Mengurangkan kahak dan lendir',
      'Rawatan berkesan untuk asma akut',
    ],
    benefitsEn: [
      'Quick relief from shortness of breath',
      'Medication reaches lungs directly',
      'Suitable for all ages',
      'Reduces phlegm and mucus',
      'Effective treatment for acute asthma',
    ],
    processMs: [
      { step: 1, title: 'Penilaian', description: 'Doktor akan menilai tahap sesak nafas anda.' },
      { step: 2, title: 'Penyediaan Ubat', description: 'Ubat nebulizer disediakan mengikut keperluan.' },
      { step: 3, title: 'Rawatan', description: 'Anda akan menghidu wap ubat selama 10-15 minit.' },
      { step: 4, title: 'Pemantauan', description: 'Doktor akan memantau peningkatan anda.' },
    ],
    processEn: [
      { step: 1, title: 'Assessment', description: 'Doctor will assess your breathing difficulty.' },
      { step: 2, title: 'Medication Preparation', description: 'Nebulizer medication prepared according to needs.' },
      { step: 3, title: 'Treatment', description: 'You will inhale the medication mist for 10-15 minutes.' },
      { step: 4, title: 'Monitoring', description: 'Doctor will monitor your improvement.' },
    ],
    suitableForMs: ['Pesakit asma', 'Bronkitis', 'Sesak nafas', 'Kanak-kanak dengan masalah pernafasan', 'Warga emas'],
    suitableForEn: ['Asthma patients', 'Bronchitis', 'Shortness of breath', 'Children with breathing problems', 'Elderly'],
    faqMs: [
      { question: 'Berapa lama rawatan nebulizer?', answer: 'Setiap sesi mengambil masa 10-15 minit bergantung kepada keperluan.' },
      { question: 'Adakah selamat untuk kanak-kanak?', answer: 'Ya, nebulizer sangat selamat dan sering digunakan untuk kanak-kanak dengan asma.' },
      { question: 'Berapa kali perlu rawatan?', answer: 'Bergantung kepada keadaan. Ada yang perlu sekali sahaja, ada yang perlu beberapa sesi.' },
      { question: 'Ada kesan sampingan?', answer: 'Kesan sampingan jarang berlaku. Mungkin ada sedikit degupan jantung laju sementara.' },
      { question: 'Boleh buat di rumah?', answer: 'Ya, untuk kes kronik, doktor boleh menasihatkan penggunaan nebulizer di rumah.' },
    ],
    faqEn: [
      { question: 'How long is nebulizer treatment?', answer: 'Each session takes 10-15 minutes depending on needs.' },
      { question: 'Is it safe for children?', answer: 'Yes, nebulizers are very safe and commonly used for children with asthma.' },
      { question: 'How many treatments needed?', answer: 'Depends on condition. Some need only once, others need several sessions.' },
      { question: 'Any side effects?', answer: 'Side effects are rare. There may be slight temporary rapid heartbeat.' },
      { question: 'Can I do it at home?', answer: 'Yes, for chronic cases, doctor can advise on home nebulizer use.' },
    ],
  },
  {
    id: 'sputum-suction',
    slug: 'sedutan-kahak',
    icon: 'Activity',
    titleMs: 'Sedutan Kahak',
    titleEn: 'Sputum Suction',
    descriptionMs: 'Prosedur untuk membuang kahak berlebihan yang sukar dikeluarkan, terutama bagi bayi dan kanak-kanak yang tidak boleh mengeluarkan kahak sendiri.',
    descriptionEn: 'Procedure to remove excess phlegm that is difficult to expel, especially for infants and children who cannot clear phlegm on their own.',
    benefitsMs: [
      'Membuang kahak yang tersumbat',
      'Melegakan pernafasan dengan segera',
      'Prosedur cepat dan selamat',
      'Sesuai untuk bayi dan kanak-kanak',
      'Mengurangkan risiko jangkitan',
    ],
    benefitsEn: [
      'Removes blocked phlegm',
      'Immediate breathing relief',
      'Quick and safe procedure',
      'Suitable for infants and children',
      'Reduces infection risk',
    ],
    processMs: [
      { step: 1, title: 'Penilaian', description: 'Doktor menilai tahap kahak dan kesukaran bernafas.' },
      { step: 2, title: 'Penyediaan', description: 'Peralatan sedutan disediakan dengan bersih.' },
      { step: 3, title: 'Sedutan', description: 'Kahak disedut dengan lembut menggunakan tiub kecil.' },
      { step: 4, title: 'Pemantauan', description: 'Pernafasan dipantau selepas prosedur.' },
    ],
    processEn: [
      { step: 1, title: 'Assessment', description: 'Doctor assesses phlegm level and breathing difficulty.' },
      { step: 2, title: 'Preparation', description: 'Suction equipment prepared cleanly.' },
      { step: 3, title: 'Suction', description: 'Phlegm is gently suctioned using a small tube.' },
      { step: 4, title: 'Monitoring', description: 'Breathing monitored after procedure.' },
    ],
    suitableForMs: ['Bayi', 'Kanak-kanak kecil', 'Pesakit lemah', 'Masalah pernafasan kronik'],
    suitableForEn: ['Infants', 'Young children', 'Weak patients', 'Chronic respiratory problems'],
    faqMs: [
      { question: 'Adakah prosedur ini menyakitkan?', answer: 'Mungkin sedikit tidak selesa tetapi tidak menyakitkan. Prosedur ini cepat.' },
      { question: 'Berapa umur minimum?', answer: 'Prosedur ini selamat untuk bayi baru lahir sekalipun.' },
      { question: 'Berapa lama prosedur ini?', answer: 'Hanya beberapa minit sahaja.' },
      { question: 'Perlukah sedutan berulang?', answer: 'Bergantung kepada jumlah kahak dan keadaan pesakit.' },
      { question: 'Apa yang perlu bawa?', answer: 'Tiada persediaan khas diperlukan. Hanya bawa pesakit ke klinik.' },
    ],
    faqEn: [
      { question: 'Is this procedure painful?', answer: 'May be slightly uncomfortable but not painful. The procedure is quick.' },
      { question: 'What is the minimum age?', answer: 'This procedure is safe even for newborns.' },
      { question: 'How long is the procedure?', answer: 'Only a few minutes.' },
      { question: 'Is repeat suction needed?', answer: 'Depends on amount of phlegm and patient condition.' },
      { question: 'What to bring?', answer: 'No special preparation needed. Just bring the patient to the clinic.' },
    ],
  },
  {
    id: 'nasal-irrigation',
    slug: 'pencucian-hidung',
    icon: 'Droplets',
    titleMs: 'Pencucian Hidung',
    titleEn: 'Nasal Irrigation',
    descriptionMs: 'Rawatan pencucian hidung untuk membersihkan lendir dan membantu melegakan hidung tersumbat. Berkesan untuk sinusitis dan alahan.',
    descriptionEn: 'Nasal washing treatment to clear mucus and help relieve nasal congestion. Effective for sinusitis and allergies.',
    benefitsMs: [
      'Membersihkan lendir dan kuman',
      'Melegakan hidung tersumbat',
      'Membantu sinusitis dan alahan',
      'Prosedur semula jadi tanpa ubat',
      'Memberikan kelegaan segera',
    ],
    benefitsEn: [
      'Clears mucus and germs',
      'Relieves nasal congestion',
      'Helps with sinusitis and allergies',
      'Natural procedure without medication',
      'Provides immediate relief',
    ],
    processMs: [
      { step: 1, title: 'Konsultasi', description: 'Doktor menilai keadaan hidung anda.' },
      { step: 2, title: 'Penyediaan', description: 'Larutan salin suam disediakan.' },
      { step: 3, title: 'Pencucian', description: 'Larutan dialirkan melalui saluran hidung.' },
      { step: 4, title: 'Penilaian', description: 'Doktor memeriksa hasil dan memberikan nasihat.' },
    ],
    processEn: [
      { step: 1, title: 'Consultation', description: 'Doctor assesses your nasal condition.' },
      { step: 2, title: 'Preparation', description: 'Warm saline solution is prepared.' },
      { step: 3, title: 'Irrigation', description: 'Solution is flushed through nasal passages.' },
      { step: 4, title: 'Assessment', description: 'Doctor checks results and provides advice.' },
    ],
    suitableForMs: ['Sinusitis', 'Alahan hidung', 'Hidung tersumbat kronik', 'Selepas pembedahan hidung'],
    suitableForEn: ['Sinusitis', 'Nasal allergies', 'Chronic nasal congestion', 'Post nasal surgery'],
    faqMs: [
      { question: 'Adakah pencucian hidung selamat?', answer: 'Ya, sangat selamat apabila dilakukan dengan teknik yang betul dan larutan steril.' },
      { question: 'Berapa kerap perlu buat?', answer: 'Bergantung kepada keadaan. Boleh dilakukan sekali atau beberapa kali seminggu.' },
      { question: 'Boleh buat sendiri di rumah?', answer: 'Ya, doktor boleh mengajar teknik dan memberikan peralatan yang sesuai.' },
      { question: 'Ada kesan sampingan?', answer: 'Jarang. Mungkin ada sedikit rasa tidak selesa pada awalnya.' },
      { question: 'Sesuai untuk kanak-kanak?', answer: 'Ya, dengan pengubahsuaian teknik yang sesuai untuk usia mereka.' },
    ],
    faqEn: [
      { question: 'Is nasal irrigation safe?', answer: 'Yes, very safe when done with proper technique and sterile solution.' },
      { question: 'How often should it be done?', answer: 'Depends on condition. Can be done once or several times a week.' },
      { question: 'Can I do it at home?', answer: 'Yes, doctor can teach the technique and provide suitable equipment.' },
      { question: 'Any side effects?', answer: 'Rare. May be slight discomfort initially.' },
      { question: 'Suitable for children?', answer: 'Yes, with technique modifications suitable for their age.' },
    ],
  },
  {
    id: 'ear-care',
    slug: 'penjagaan-telinga',
    icon: 'Ear',
    titleMs: 'Penjagaan Telinga (Microsuction)',
    titleEn: 'Ear Care (Microsuction)',
    descriptionMs: 'Perkhidmatan pembersihan telinga profesional menggunakan teknologi microsuction yang selamat dan berkesan. Membuang tahi telinga tanpa air.',
    descriptionEn: 'Professional ear cleaning service using safe and effective microsuction technology. Removes earwax without water.',
    benefitsMs: [
      'Teknik microsuction moden dan selamat',
      'Tiada penggunaan air - mengelakkan jangkitan',
      'Pandangan terus dengan mikroskop/kamera',
      'Sesuai untuk pesakit dengan masalah telinga',
      'Prosedur cepat dan selesa',
    ],
    benefitsEn: [
      'Modern and safe microsuction technique',
      'No water used - avoids infections',
      'Direct view with microscope/camera',
      'Suitable for patients with ear problems',
      'Quick and comfortable procedure',
    ],
    processMs: [
      { step: 1, title: 'Pemeriksaan', description: 'Doktor memeriksa saluran telinga dengan otoskop.' },
      { step: 2, title: 'Penilaian', description: 'Menentukan jenis dan jumlah tahi telinga.' },
      { step: 3, title: 'Microsuction', description: 'Tahi telinga disedut dengan lembut menggunakan alat khas.' },
      { step: 4, title: 'Pemeriksaan Akhir', description: 'Memastikan telinga bersih dan sihat.' },
    ],
    processEn: [
      { step: 1, title: 'Examination', description: 'Doctor examines ear canal with otoscope.' },
      { step: 2, title: 'Assessment', description: 'Determines type and amount of earwax.' },
      { step: 3, title: 'Microsuction', description: 'Earwax is gently suctioned using special equipment.' },
      { step: 4, title: 'Final Check', description: 'Ensuring ear is clean and healthy.' },
    ],
    suitableForMs: ['Tahi telinga berlebihan', 'Masalah pendengaran', 'Gatal telinga', 'Sebelum pemeriksaan telinga', 'Pesakit tiub telinga'],
    suitableForEn: ['Excess earwax', 'Hearing problems', 'Itchy ears', 'Before ear examination', 'Ear tube patients'],
    faqMs: [
      { question: 'Apa itu microsuction?', answer: 'Microsuction adalah teknik pembersihan telinga menggunakan sedutan lembut tanpa air, lebih selamat dari syringing.' },
      { question: 'Adakah ia menyakitkan?', answer: 'Tidak, prosedur ini tidak menyakitkan. Mungkin ada bunyi sedutan yang sedikit kuat.' },
      { question: 'Berapa kerap perlu cuci telinga?', answer: 'Bergantung kepada penghasilan tahi telinga. Ada yang perlu setiap 6-12 bulan.' },
      { question: 'Bolehkah pakai cotton bud?', answer: 'Tidak digalakkan kerana ia boleh menolak tahi telinga lebih dalam dan merosakkan gendang telinga.' },
      { question: 'Sesuai untuk kanak-kanak?', answer: 'Ya, microsuction sesuai untuk semua umur termasuk kanak-kanak.' },
    ],
    faqEn: [
      { question: 'What is microsuction?', answer: 'Microsuction is an ear cleaning technique using gentle suction without water, safer than syringing.' },
      { question: 'Is it painful?', answer: 'No, the procedure is painless. There may be a slightly loud suction sound.' },
      { question: 'How often should ears be cleaned?', answer: 'Depends on earwax production. Some need it every 6-12 months.' },
      { question: 'Can I use cotton buds?', answer: 'Not recommended as it can push earwax deeper and damage the eardrum.' },
      { question: 'Suitable for children?', answer: 'Yes, microsuction is suitable for all ages including children.' },
    ],
  },
  {
    id: 'circumcision',
    slug: 'khatan',
    icon: 'Scissors',
    titleMs: 'Khatan: Kanak-kanak & Dewasa',
    titleEn: 'Circumcision: Children & Adults',
    descriptionMs: 'Perkhidmatan khatan profesional untuk kanak-kanak dan dewasa. Dilakukan oleh doktor berpengalaman dengan teknik moden dan penjagaan selepas prosedur yang teliti.',
    descriptionEn: 'Professional circumcision service for children and adults. Performed by experienced doctors with modern techniques and careful post-procedure care.',
    benefitsMs: [
      'Doktor berpengalaman dalam prosedur khatan',
      'Teknik moden dengan minimum kesakitan',
      'Anastesia tempatan untuk keselesaan',
      'Penjagaan selepas prosedur yang teliti',
      'Persekitaran klinik yang bersih dan selesa',
    ],
    benefitsEn: [
      'Experienced doctors in circumcision procedures',
      'Modern technique with minimal pain',
      'Local anesthesia for comfort',
      'Careful post-procedure care',
      'Clean and comfortable clinic environment',
    ],
    processMs: [
      { step: 1, title: 'Konsultasi', description: 'Perbincangan tentang prosedur dan persediaan.' },
      { step: 2, title: 'Persediaan', description: 'Pembersihan kawasan dan anastesia tempatan.' },
      { step: 3, title: 'Prosedur', description: 'Khatan dilakukan dengan teknik yang sesuai.' },
      { step: 4, title: 'Penjagaan Selepas', description: 'Arahan penjagaan luka dan temujanji susulan.' },
    ],
    processEn: [
      { step: 1, title: 'Consultation', description: 'Discussion about procedure and preparation.' },
      { step: 2, title: 'Preparation', description: 'Area cleaning and local anesthesia.' },
      { step: 3, title: 'Procedure', description: 'Circumcision performed with appropriate technique.' },
      { step: 4, title: 'Aftercare', description: 'Wound care instructions and follow-up appointment.' },
    ],
    suitableForMs: ['Kanak-kanak lelaki', 'Remaja', 'Dewasa lelaki', 'Atas sebab kesihatan atau agama'],
    suitableForEn: ['Boys', 'Teenagers', 'Adult males', 'For health or religious reasons'],
    faqMs: [
      { question: 'Berapa umur sesuai untuk khatan?', answer: 'Khatan boleh dilakukan pada sebarang umur. Ramai memilih waktu sekolah rendah atau sebelum akil baligh.' },
      { question: 'Berapa lama prosedur?', answer: 'Prosedur mengambil masa kira-kira 30-45 minit.' },
      { question: 'Berapa lama untuk pulih?', answer: 'Biasanya 1-2 minggu untuk penyembuhan asas, 4-6 minggu untuk sembuh sepenuhnya.' },
      { question: 'Adakah ia menyakitkan?', answer: 'Anastesia tempatan diberikan jadi tidak sakit semasa prosedur. Ubat tahan sakit diberikan untuk selepasnya.' },
      { question: 'Apa persediaan yang diperlukan?', answer: 'Mandi bersih sebelum datang, pakai seluar longgar, dan puasa jika prosedur pagi.' },
      { question: 'Bilakah boleh mandi selepas khatan?', answer: 'Biasanya selepas 24-48 jam dengan penjagaan yang betul. Doktor akan memberikan arahan.' },
    ],
    faqEn: [
      { question: 'What age is suitable for circumcision?', answer: 'Circumcision can be done at any age. Many choose during primary school or before puberty.' },
      { question: 'How long is the procedure?', answer: 'The procedure takes about 30-45 minutes.' },
      { question: 'How long to recover?', answer: 'Usually 1-2 weeks for basic healing, 4-6 weeks for complete recovery.' },
      { question: 'Is it painful?', answer: 'Local anesthesia is given so there is no pain during procedure. Pain medication is provided for after.' },
      { question: 'What preparation is needed?', answer: 'Clean shower before coming, wear loose pants, and fast if morning procedure.' },
      { question: 'When can I shower after circumcision?', answer: 'Usually after 24-48 hours with proper care. Doctor will provide instructions.' },
    ],
  },
  {
    id: 'lump-wart',
    slug: 'ketumbuhan-ketuat',
    icon: 'Circle',
    titleMs: 'Rawatan Ketumbuhan & Ketuat',
    titleEn: 'Lump & Wart Treatment',
    descriptionMs: 'Perkhidmatan pembedahan kecil untuk membuang ketumbuhan kulit, ketuat, kista, dan lipoma. Dilakukan dengan teknik selamat dan minimum parut.',
    descriptionEn: 'Minor surgery services to remove skin lumps, warts, cysts, and lipomas. Performed with safe techniques and minimal scarring.',
    benefitsMs: [
      'Prosedur di klinik - tiada perlu ke hospital',
      'Anastesia tempatan untuk keselesaan',
      'Teknik minimum parut',
      'Penyembuhan cepat',
      'Pemeriksaan histologi jika perlu',
    ],
    benefitsEn: [
      'In-clinic procedure - no hospital needed',
      'Local anesthesia for comfort',
      'Minimal scarring technique',
      'Quick healing',
      'Histology examination if needed',
    ],
    processMs: [
      { step: 1, title: 'Pemeriksaan', description: 'Doktor memeriksa ketumbuhan atau ketuat.' },
      { step: 2, title: 'Perbincangan', description: 'Pilihan rawatan dibincangkan.' },
      { step: 3, title: 'Prosedur', description: 'Pembedahan kecil dengan anastesia tempatan.' },
      { step: 4, title: 'Penjagaan Luka', description: 'Arahan penjagaan dan temujanji susulan.' },
    ],
    processEn: [
      { step: 1, title: 'Examination', description: 'Doctor examines the lump or wart.' },
      { step: 2, title: 'Discussion', description: 'Treatment options are discussed.' },
      { step: 3, title: 'Procedure', description: 'Minor surgery with local anesthesia.' },
      { step: 4, title: 'Wound Care', description: 'Care instructions and follow-up appointment.' },
    ],
    suitableForMs: ['Ketuat (warts)', 'Kista (cysts)', 'Lipoma', 'Ketumbuhan kulit', 'Skin tags'],
    suitableForEn: ['Warts', 'Cysts', 'Lipomas', 'Skin lumps', 'Skin tags'],
    faqMs: [
      { question: 'Bilakah perlu buang ketumbuhan?', answer: 'Jika ia membesar, sakit, berdarah, berubah rupa, atau mengganggu aktiviti harian.' },
      { question: 'Adakah prosedur ini sakit?', answer: 'Anastesia tempatan diberikan jadi tidak sakit semasa prosedur.' },
      { question: 'Berapa lama prosedur?', answer: 'Bergantung kepada saiz dan jenis. Biasanya 15-45 minit.' },
      { question: 'Adakah ketumbuhan akan tumbuh semula?', answer: 'Jarang berlaku jika dibuang sepenuhnya. Sesetengah jenis mungkin berulang.' },
      { question: 'Perlu jahitan ke?', answer: 'Bergantung kepada saiz dan lokasi. Doktor akan menerangkan semasa konsultasi.' },
      { question: 'Boleh pergi kerja selepas prosedur?', answer: 'Biasanya ya, untuk prosedur kecil. Bergantung kepada jenis kerja dan lokasi luka.' },
    ],
    faqEn: [
      { question: 'When should a lump be removed?', answer: 'If it is growing, painful, bleeding, changing appearance, or interfering with daily activities.' },
      { question: 'Is the procedure painful?', answer: 'Local anesthesia is given so there is no pain during procedure.' },
      { question: 'How long is the procedure?', answer: 'Depends on size and type. Usually 15-45 minutes.' },
      { question: 'Will the lump grow back?', answer: 'Rarely if completely removed. Some types may recur.' },
      { question: 'Are stitches needed?', answer: 'Depends on size and location. Doctor will explain during consultation.' },
      { question: 'Can I go to work after?', answer: 'Usually yes, for minor procedures. Depends on type of work and wound location.' },
    ],
  },
];

export function getServiceBySlug(slug: string): ServiceContent | undefined {
  return SERVICE_CONTENT.find(service => service.slug === slug);
}
