import { FilePlus2, Loader2, Pencil, Save, Send } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { Link, useNavigate, useParams } from "react-router-dom";

import { LivePreview } from "@/components/editor/LivePreview";
import { WebsiteMediaUploader } from "@/components/editor/WebsiteMediaUploader";
import { useEditorDirtyState } from "@/components/editor/useEditorDirtyNavigation";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { fetchResourceForEditor, listResourceSummaries, newResourceId, publishResourceDraft, saveResourceDraft, type WebsiteResourceSummary } from "@/features/website-cms/api/resources";
import { parseWebsiteResourceDraft } from "@/features/website-cms/resources/registry";
import type { WebsiteResourceType } from "@/features/website-cms/resources/types";
import { sanitizeRichHtml } from "@/lib/sanitize-rich-html";
import { ResourceVersionsPanel } from "@/pages/editor/ResourceVersionsPanel";

type EditableType = Exclude<WebsiteResourceType, "service">;
type FieldKind = "boolean" | "list" | "number" | "select" | "text" | "textarea";
interface FieldDefinition { key: string; kind: FieldKind; label: string; options?: string[]; required?: boolean; }
interface ResourceConfig { singular: string; plural: string; route: string; type: EditableType; fields: FieldDefinition[]; defaults: Record<string, unknown>; }

const configs: Record<EditableType, ResourceConfig> = {
  team_member: { type:"team_member", route:"team", singular:"profile", plural:"Team", defaults:{ type:"doctor",nameMs:"",nameEn:"",titleMs:"",titleEn:"",bioMs:"",bioEn:"",expertiseMs:[],expertiseEn:[],qualifications:[],yearsExperience:0,photoUrl:"",isActive:true,displayOrder:0 }, fields:[{key:"type",label:"Profile type",kind:"select",options:["doctor","team"]},{key:"nameMs",label:"Name (Malay)",kind:"text",required:true},{key:"nameEn",label:"Name (English)",kind:"text"},{key:"titleMs",label:"Title (Malay)",kind:"text",required:true},{key:"titleEn",label:"Title (English)",kind:"text"},{key:"bioMs",label:"Biography (Malay)",kind:"textarea",required:true},{key:"bioEn",label:"Biography (English)",kind:"textarea"},{key:"expertiseMs",label:"Expertise (Malay, one per line)",kind:"list"},{key:"expertiseEn",label:"Expertise (English, one per line)",kind:"list"},{key:"qualifications",label:"Qualifications (one per line)",kind:"list"},{key:"yearsExperience",label:"Years of experience",kind:"number"},{key:"photoUrl",label:"Photo URL",kind:"text"},{key:"isActive",label:"Visible on website",kind:"boolean"},{key:"displayOrder",label:"Display order",kind:"number"}] },
  blog_post: { type:"blog_post",route:"blog",singular:"post",plural:"Blog",defaults:{slug:"",titleMs:"",titleEn:"",excerptMs:"",excerptEn:"",contentMs:"",contentEn:"",categoryId:null,featuredImage:"",readingTime:1,status:"draft",scheduledAt:null},fields:[{key:"slug",label:"Slug",kind:"text",required:true},{key:"titleMs",label:"Title (Malay)",kind:"text",required:true},{key:"titleEn",label:"Title (English)",kind:"text"},{key:"excerptMs",label:"Excerpt (Malay)",kind:"textarea",required:true},{key:"excerptEn",label:"Excerpt (English)",kind:"textarea"},{key:"contentMs",label:"Body HTML (Malay)",kind:"textarea",required:true},{key:"contentEn",label:"Body HTML (English)",kind:"textarea"},{key:"featuredImage",label:"Featured image URL",kind:"text"},{key:"readingTime",label:"Reading time (minutes)",kind:"number"},{key:"status",label:"Publication status",kind:"select",options:["draft","scheduled","published","archived"]},{key:"scheduledAt",label:"Schedule (ISO date, optional)",kind:"text"}] },
  gallery_image: { type:"gallery_image",route:"gallery",singular:"item",plural:"Gallery",defaults:{url:"",altMs:"",altEn:"",tags:[],displayOrder:0,visible:true},fields:[{key:"url",label:"Image, video or YouTube URL",kind:"text",required:true},{key:"altMs",label:"Alt text (Malay)",kind:"text",required:true},{key:"altEn",label:"Alt text (English)",kind:"text"},{key:"tags",label:"Tags (one per line)",kind:"list"},{key:"displayOrder",label:"Display order",kind:"number"},{key:"visible",label:"Visible on website",kind:"boolean"}] },
  review: { type:"review",route:"reviews",singular:"review",plural:"Reviews",defaults:{nameMs:"",nameEn:"",reviewTextMs:"",reviewTextEn:"",rating:5,sourceLabel:"Klinik Awfa",status:"draft",displayOrder:0},fields:[{key:"nameMs",label:"Public display name (Malay)",kind:"text",required:true},{key:"nameEn",label:"Public display name (English)",kind:"text"},{key:"reviewTextMs",label:"Review (Malay)",kind:"textarea",required:true},{key:"reviewTextEn",label:"Review (English)",kind:"textarea"},{key:"rating",label:"Rating (1–5)",kind:"number"},{key:"sourceLabel",label:"Source label",kind:"text",required:true},{key:"status",label:"Publication status",kind:"select",options:["draft","published","archived"]},{key:"displayOrder",label:"Display order",kind:"number"}] },
};

export function ResourceListPage({ type }: { type: EditableType }) {
  const config = configs[type]; const [items,setItems]=useState<WebsiteResourceSummary[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState(false);
  useEffect(()=>{let active=true;void listResourceSummaries(type).then((rows)=>{if(active)setItems(rows)}).catch(()=>{if(active)setError(true)}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[type]);
  return <section className="space-y-6"><header className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><p className="text-sm font-medium text-blue-700">Public content</p><h1 className="mt-1 text-2xl font-semibold">{config.plural}</h1><p className="mt-2 text-sm text-slate-600">Draft, preview and publish website {config.plural.toLowerCase()} content.</p></div><Button asChild><Link to={`/editor/${config.route}/new`}><FilePlus2 className="mr-2 h-4 w-4"/>Add {config.singular}</Link></Button></header>{loading&&<p className="rounded-xl border bg-white p-5 text-sm" role="status"><Loader2 className="mr-2 inline h-4 w-4 animate-spin"/>Loading {config.plural.toLowerCase()}</p>}{error&&<p className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-800" role="alert">{config.plural} could not be loaded.</p>}{!loading&&!error&&items.length===0&&<div className="rounded-xl border border-dashed bg-white p-8 text-center"><p className="font-medium">No {config.plural.toLowerCase()} yet</p><p className="mt-1 text-sm text-slate-600">Create a private draft to get started.</p></div>}{!loading&&!error&&items.length>0&&<ul className="divide-y overflow-hidden rounded-xl border bg-white shadow-sm">{items.map((item)=><li className="flex items-center justify-between gap-4 p-5" key={item.id}><div className="min-w-0"><div className="flex items-center gap-2"><h2 className="truncate font-semibold">{item.title}</h2><Badge variant={item.status==="published"?"default":"outline"}>{item.status}</Badge></div><p className="mt-1 line-clamp-1 text-xs text-slate-500">{item.subtitle}</p></div><Button asChild size="sm" variant="outline"><Link to={`/editor/${config.route}/${item.id}`}><Pencil className="mr-2 h-4 w-4"/>Edit</Link></Button></li>)}</ul>}</section>;
}

export function ResourceEditorPage({ type }: { type: EditableType }) {
  const config=configs[type]; const {id="new"}=useParams(); const isNew=id==="new"; const resourceId=useMemo(()=>isNew?newResourceId():id,[id,isNew]); const navigate=useNavigate();
  const [value,setValue]=useState<Record<string,unknown>>({...config.defaults}); const [revision,setRevision]=useState(0); const [loading,setLoading]=useState(!isNew); const [dirty,setDirty]=useState(false); const [busy,setBusy]=useState(false); const [notice,setNotice]=useState<{tone:"error"|"success";text:string}|null>(null); useEditorDirtyState(dirty);
  const reload=async()=>{const result=await fetchResourceForEditor(type,resourceId);if(!result)throw new Error("not found");setValue(result.payload as unknown as Record<string,unknown>);setRevision(result.revision);setDirty(false)};
  useEffect(()=>{if(isNew){setValue({...config.defaults});setRevision(0);setLoading(false);return;}let active=true;setLoading(true);void fetchResourceForEditor(type,id).then((result)=>{if(!active)return;if(!result)throw new Error("not found");setValue(result.payload as unknown as Record<string,unknown>);setRevision(result.revision)}).catch(()=>{if(active)setNotice({tone:"error",text:`This ${config.singular} could not be loaded.`})}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[config.defaults,config.singular,id,isNew,type]);
  const update=(key:string,next:unknown)=>{setValue((current)=>({...current,[key]:next}));setDirty(true);setNotice(null)};
  const validated=()=>{try{return parseWebsiteResourceDraft(type,value)}catch(error){setNotice({tone:"error",text:error instanceof Error?error.message:"Complete all required fields."});return null}};
  const save=async()=>{const payload=validated();if(!payload)return;setBusy(true);try{await saveResourceDraft({baseRevision:revision,payload,resourceId,resourceType:type,updatedAt:null});setDirty(false);setNotice({tone:"success",text:"Draft saved privately."});if(isNew)navigate(`/editor/${config.route}/${resourceId}`,{replace:true})}catch{setNotice({tone:"error",text:"Draft could not be saved. Your changes remain in this form."})}finally{setBusy(false)}};
  const publish=async()=>{const payload=validated();if(!payload)return;setBusy(true);try{await saveResourceDraft({baseRevision:revision,payload,resourceId,resourceType:type,updatedAt:null});const next=await publishResourceDraft(type,resourceId,revision);setRevision(next);setDirty(false);setNotice({tone:"success",text:`${config.singular[0].toUpperCase()+config.singular.slice(1)} published successfully.`});if(isNew)navigate(`/editor/${config.route}/${resourceId}`,{replace:true})}catch(error){setNotice({tone:"error",text:error instanceof Error?error.message:"Content could not be published."})}finally{setBusy(false)}};
  if(loading)return <p className="rounded-xl border bg-white p-5 text-sm" role="status"><Loader2 className="mr-2 inline h-4 w-4 animate-spin"/>Loading {config.singular}</p>;
  return <section className="space-y-8"><header className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><p className="text-sm font-medium text-blue-700">{config.plural}</p><h1 className="mt-1 text-2xl font-semibold">{isNew?`New ${config.singular}`:String(value.nameMs??value.titleMs??value.altMs??"Edit content")}</h1><p className="mt-1 text-xs text-slate-500">Revision {revision}</p></div><div className="flex flex-wrap gap-2"><Button variant="outline" onClick={()=>navigate(`/editor/${config.route}`)}>Back</Button><Button variant="outline" disabled={busy} onClick={()=>void save()}><Save className="mr-2 h-4 w-4"/>Save draft</Button><Button disabled={busy} onClick={()=>void publish()}><Send className="mr-2 h-4 w-4"/>Publish</Button></div></header>{notice&&<p className={`rounded-lg border p-3 text-sm ${notice.tone==="success"?"border-emerald-200 bg-emerald-50 text-emerald-800":"border-red-200 bg-red-50 text-red-800"}`} role={notice.tone==="error"?"alert":"status"}>{notice.text}</p>}<div className="grid gap-5 rounded-xl border bg-white p-6 shadow-sm md:grid-cols-2">{config.fields.map((field)=><div key={field.key}><ResourceField field={field} onChange={(next)=>update(field.key,next)} value={value[field.key]}/>{["photoUrl","featuredImage","url"].includes(field.key)&&<WebsiteMediaUploader folder={type==="team_member"?"team":type==="blog_post"?"blog":"gallery"} onUploaded={(url)=>update(field.key,url)}/>}</div>)}</div><LivePreview title={`${config.singular[0].toUpperCase()+config.singular.slice(1)} live preview`}><ResourcePreview type={type} value={value}/></LivePreview>{!isNew&&<ResourceVersionsPanel disabled={busy||dirty} onRestored={reload} resourceId={resourceId} resourceLabel={config.singular} resourceType={type}/>}</section>;
}

function ResourceField({field,value,onChange}:{field:FieldDefinition;value:unknown;onChange:(value:unknown)=>void}){const id=`resource-${field.key}`;if(field.kind==="boolean")return <label className="flex items-center gap-3 rounded-lg border p-4"><input checked={Boolean(value)} onChange={(e)=>onChange(e.target.checked)} type="checkbox"/><span className="text-sm font-medium">{field.label}</span></label>;if(field.kind==="select")return <div className="space-y-2"><Label htmlFor={id}>{field.label}</Label><select className="h-10 w-full rounded-md border border-input bg-background px-3 text-sm" id={id} value={String(value??"")} onChange={(e)=>onChange(e.target.value)}>{field.options?.map((option)=><option key={option} value={option}>{option}</option>)}</select></div>;if(field.kind==="list")return <div className="space-y-2"><Label htmlFor={id}>{field.label}</Label><Textarea id={id} rows={5} value={Array.isArray(value)?value.join("\n"):""} onChange={(e)=>onChange(e.target.value.split("\n").map((x)=>x.trim()).filter(Boolean))}/></div>;if(field.kind==="textarea")return <div className="space-y-2 md:col-span-2"><Label htmlFor={id}>{field.label}{field.required?" *":""}</Label><Textarea id={id} rows={7} value={String(value??"")} onChange={(e)=>onChange(e.target.value)}/></div>;return <div className="space-y-2"><Label htmlFor={id}>{field.label}{field.required?" *":""}</Label><Input id={id} type={field.kind==="number"?"number":"text"} value={String(value??"")} onChange={(e)=>onChange(field.kind==="number"?Number(e.target.value):e.target.value)}/></div>}

function ResourcePreview({type,value}:{type:EditableType;value:Record<string,unknown>}){if(type==="review")return <figure className="mx-auto max-w-xl px-6 py-16 text-center"><div className="text-amber-500">{"★".repeat(Number(value.rating??5))}</div><blockquote className="mt-5 text-xl leading-8 text-slate-800">“{String(value.reviewTextMs??"")}”</blockquote><figcaption className="mt-4 font-semibold">{String(value.nameMs??"")}</figcaption></figure>;if(type==="gallery_image")return <figure className="mx-auto max-w-3xl p-8">{String(value.url??"").match(/\.(mp4|webm)$/i)?<video className="w-full rounded-xl" controls={false} src={String(value.url)}/>:<img alt={String(value.altMs??"")} className="max-h-[560px] w-full rounded-xl object-cover" src={String(value.url??"")}/>}<figcaption className="mt-3 text-sm text-slate-600">{String(value.altMs??"")}</figcaption></figure>;if(type==="team_member")return <article className="mx-auto max-w-3xl px-6 py-14 text-center">{value.photoUrl&&<img alt={String(value.nameMs??"")} className="mx-auto h-40 w-40 rounded-full object-cover" src={String(value.photoUrl)}/>}<h1 className="mt-5 text-3xl font-bold">{String(value.nameMs??"")}</h1><p className="mt-2 font-medium text-blue-700">{String(value.titleMs??"")}</p><p className="mt-5 leading-7 text-slate-700">{String(value.bioMs??"")}</p></article>;return <article className="mx-auto max-w-3xl px-6 py-14"><h1 className="text-4xl font-bold">{String(value.titleMs??"")}</h1><p className="mt-4 text-lg text-slate-600">{String(value.excerptMs??"")}</p><div className="prose mt-8 max-w-none" dangerouslySetInnerHTML={{__html:sanitizeRichHtml(String(value.contentMs??""))}}/></article>}
